    <div class="site-home-dialogs">
    <noscript><div class="noscript-notice">Bật JavaScript để sử dụng form báo giá và các chức năng tương tác. Nội dung trang vẫn xem được.</div></noscript>

    <div class="modal fade" id="quoteModal" tabindex="-1" aria-labelledby="quoteTitle" aria-hidden="true"><div class="modal-dialog modal-dialog-centered modal-lg modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><div><p class="modal-brand">{{ $website->site_name }}</p><h2 class="modal-title fs-4" id="quoteTitle">Nhận báo giá chuyến đi</h2></div><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Đóng"></button></div><div class="modal-body">
        <div class="alert demo-notice" id="demoNotice" role="note" hidden>Gửi form để CamKheTravel tiếp nhận yêu cầu tư vấn. Đây chưa phải xác nhận đặt xe.</div>
        <form id="requestForm" novalidate>
            <div class="request-type-switch"><label class="form-label" for="requestType">Nhu cầu của bạn</label><select class="form-select" name="type" id="requestType"><option value="trip">Chuyến đi riêng</option><option value="partner">Hợp tác đối tác</option><option value="wedding">Xe cưới</option><option value="shared">Xe ghép</option></select></div><input type="hidden" name="service" id="requestService" value=""><input type="hidden" name="service_id" id="requestServiceId" value="">
            <div class="honeypot" aria-hidden="true"><label for="requestWebsite">Website phụ</label><input id="requestWebsite" name="website" tabindex="-1" autocomplete="off"></div>
            <div class="row g-3">
                <div class="col-md-6"><label class="form-label" for="requestName">Họ và tên <span aria-hidden="true">*</span></label><input class="form-control" id="requestName" name="name" required minlength="2" maxlength="100" autocomplete="name"><div class="invalid-feedback">Nhập họ tên từ 2 đến 100 ký tự.</div></div>
                <div class="col-md-6"><label class="form-label" for="requestPhone">Số điện thoại <span aria-hidden="true">*</span></label><input class="form-control" id="requestPhone" name="phone" type="tel" inputmode="tel" required maxlength="24" autocomplete="tel"><div class="invalid-feedback">Nhập số di động Việt Nam hợp lệ.</div></div>
                <div class="col-12" id="companyGroup" hidden><label class="form-label" for="requestCompany">Công ty / Đơn vị tổ chức tour <span aria-hidden="true">*</span></label><input class="form-control" id="requestCompany" name="company" maxlength="180" autocomplete="organization"><div class="invalid-feedback">Nhập tên công ty hoặc đơn vị tổ chức.</div></div>
                <div class="col-md-6"><label class="form-label" for="requestPickup">Điểm đón</label><input class="form-control" id="requestPickup" name="pickup" maxlength="180" placeholder="Ví dụ: Cẩm Khê, Phú Thọ"><div class="invalid-feedback">Nhập điểm đón.</div></div>
                <div class="col-md-6"><label class="form-label" for="requestDestination">Điểm đến</label><input class="form-control" id="requestDestination" name="destination" maxlength="180" placeholder="Địa điểm hoặc lịch trình dự kiến"><div class="invalid-feedback">Nhập điểm đến.</div></div>
                <div class="col-md-6"><label class="form-label" for="requestDeparture">Ngày đi dự kiến</label><input class="form-control" id="requestDeparture" name="departure" type="date"><div class="invalid-feedback">Ngày đi không được trước hôm nay.</div></div>
                <div class="col-md-6" id="returnGroup"><label class="form-label" for="requestReturn">Ngày về (nếu có)</label><input class="form-control" id="requestReturn" name="returnDate" type="date"><div class="invalid-feedback">Ngày về không được trước ngày đi.</div></div>
                <div class="col-md-6"><label class="form-label" for="requestVehicle">Loại xe</label><select class="form-select" id="requestVehicle" name="vehicle"><option value="Cần tư vấn">Cần tư vấn</option>@foreach ($fleetTypes as $vehicle)<option value="{{ $vehicle['title'] }}">{{ $vehicle['title'] }}</option>@endforeach<option value="Xe cưới">Xe cưới</option></select></div>
                <div class="col-md-6"><label class="form-label" for="requestPassengers">Số khách / Quy mô đoàn</label><input class="form-control" id="requestPassengers" name="passengers" maxlength="80" placeholder="Ví dụ: 4 người, 2 vali"></div>
                <div class="col-md-6"><label class="form-label" for="requestPickupTime">Giờ đón dự kiến (nếu có)</label><input class="form-control" id="requestPickupTime" name="pickupTime" type="time"></div>
                <div class="col-md-6" id="weddingGroup" hidden><label class="form-label" for="requestWeddingRole">Nhu cầu xe cưới</label><select class="form-select" id="requestWeddingRole" name="weddingRole" disabled><option value="">Cần tư vấn</option><option>Xe dâu</option><option>Đưa đón gia đình</option><option>Cả hai</option></select></div>
                <div class="col-12"><label class="form-label" for="requestNotes">Yêu cầu thêm</label><textarea class="form-control" id="requestNotes" name="notes" rows="3" maxlength="2000" placeholder="Giờ đón, điểm dừng, số chuyến, nhu cầu hợp tác..."></textarea></div>
                <div class="col-12"><div class="form-check"><input class="form-check-input" id="requestConsent" name="consent" type="checkbox" required><label class="form-check-label" for="requestConsent">Tôi đồng ý cung cấp thông tin để được liên hệ tư vấn về yêu cầu này.</label><div class="invalid-feedback">Cần đồng ý trước khi tiếp tục.</div></div><p class="form-hint">Đây là yêu cầu tư vấn, chưa phải xác nhận đặt xe hoặc giá cuối cùng.</p></div>
            </div>
            <div id="formError" class="alert alert-danger mt-3" role="alert" hidden></div>
            <div class="form-submit"><button type="button" class="btn btn-soft" data-bs-dismiss="modal">Để sau</button><button type="submit" class="btn btn-brand" id="requestSubmit"><span data-submit-label>Gửi yêu cầu tư vấn</span> <x-site-icon name="arrow" /></button></div>
        </form>
        <div id="requestResult" hidden aria-live="polite"><span class="result-icon"><x-site-icon name="check" /></span><h3 id="resultTitle">Đã gửi yêu cầu tư vấn</h3><p id="resultDescription">Hệ thống đã tiếp nhận yêu cầu. Đây chưa phải xác nhận đặt xe; CamKheTravel cần liên hệ để thống nhất lịch trình và chi phí.</p><label class="form-label" for="requestSummary">Nội dung yêu cầu</label><textarea id="requestSummary" class="form-control request-summary" rows="9" readonly></textarea><div class="result-actions">@if ($frontendConfig['phone'])<button type="button" class="btn btn-white" data-contact="phone">Gọi trao đổi</button>@endif @if ($frontendConfig['zaloUrl'])<button type="button" class="btn btn-white" data-contact="zalo">Nhắn Zalo</button>@endif <button type="button" class="btn btn-brand" id="copySummary"><x-site-icon name="copy" /> Sao chép nội dung</button><button type="button" class="btn btn-outline-brand" id="editRequest">Chỉnh sửa yêu cầu</button></div><p id="copyStatus" class="form-hint mt-3" role="status"></p></div>
    </div></div></div></div>

    <div class="modal fade" id="vehicleModal" tabindex="-1" aria-labelledby="vehicleTitle" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h2 class="modal-title fs-4" id="vehicleTitle">Thông tin xe</h2><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Đóng"></button></div><div class="modal-body"><img id="vehicleDetailImage" class="vehicle-detail-image" src="{{ $noImageUrl }}" alt="Ảnh xe mặc định" width="700" height="500"><p id="vehicleDetailDescription"></p><p class="form-hint">Ảnh minh họa. Dòng xe, sức chứa và hành lý sẽ được xác nhận khi trao đổi lịch trình.</p><button type="button" class="btn btn-brand w-100" id="quoteVehicle">Tư vấn xe này <x-site-icon name="arrow" /></button></div></div></div></div>

    <div class="modal fade" id="privacyModal" tabindex="-1" aria-labelledby="privacyTitle" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h2 id="privacyTitle" class="modal-title fs-4">Thông tin dữ liệu</h2><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Đóng"></button></div><div class="modal-body"><p id="privacyDataText">Thông tin trong biểu mẫu được gửi về website và lưu thành yêu cầu liên hệ để CamKheTravel xử lý. Việc gửi yêu cầu chưa xác nhận chuyến xe, lịch trình hoặc giá.</p><p>Thông tin được dùng để liên hệ về yêu cầu tư vấn của bạn.</p></div></div></div></div>
    </div>
