@include('frontend.landing.parts.corporate-film.hero', ['args' => ['landing' => $landingContent]])
@include('frontend.landing.parts.communications.positioning', ['args' => ['landing' => $landingContent]])
@include('frontend.landing.parts.corporate-film.benefits', ['args' => ['landing' => $landingContent]])
@include('frontend.landing.parts.communications.solutions', ['args' => ['landing' => $landingContent]])
@include('frontend.landing.parts.corporate-film.pricing', ['args' => ['landing' => $landingContent]])
@include('frontend.landing.parts.corporate-film.showcase', ['args' => ['landing' => $landingContent]])
@include('frontend.landing.parts.corporate-film.bts', ['args' => ['landing' => $landingContent]])
@include('frontend.landing.parts.communications.strategy', ['args' => ['landing' => $landingContent]])
@include('frontend.landing.parts.communications.process', ['args' => ['landing' => $landingContent]])
@include('frontend.landing.parts.communications.faq', ['args' => ['landing' => $landingContent]])
@include('frontend.landing.parts.communications.contact', ['args' => ['landing' => $landingContent, 'success_class' => 'film-form-success']])
